export const PEG_FRICTION = 1;
export const PEG_RESTITUTION = 0.5;
export const PEG_RADIUS = 5;
export const PEG_DIAMETER = PEG_RADIUS * 2
export const CHIP_FRICTION = 1;
export const CHIP_RESTITUTION = 0.5;
export const CHIP_RADIUS = 20;
export const CHIP_DIAMETER = CHIP_RADIUS * 2;
export const WALL_FRICTION = 1;
export const WALL_RESTITUTION = 0.5;
